# Generated by Skyramp v1.3.23 on 2026-05-05 22:47:31.338148304 +0000 UTC m=+81.530488160
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output recipes_pagination_last_page_boundary_integration_test.py \
# 		--output-dir /home/runner/work/mealie/mealie/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/mealie/mealie/tests/scenario_recipes-pagination-last-page-boundary.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:9000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    recipes_POST_request_body = r'''{
        "name": "Testbot-LastPageA-1746461298"
    }'''
    
    # Execute Request
    recipes_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes",
        method="POST",
        body=recipes_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert recipes_POST_response.status_code == 201

    # Request Body
    recipes_POST_1_request_body = r'''{
        "name": "Testbot-LastPageB-1746461298"
    }'''
    
    # Execute Request
    recipes_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes",
        method="POST",
        body=recipes_POST_1_request_body,
        headers=headers
    )
    # Generated Assertions
    assert recipes_POST_1_response.status_code == 201

    # Execute Request
    recipes_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes",
        method="GET",
        headers=headers,
        query_params={
            "page": ["2"],
            "perPage": ["1"]
        }
    )
    # Generated Assertions
    assert recipes_GET_response.status_code == 200
    assert skyramp.get_response_value(recipes_GET_response, "page") == 2
    assert skyramp.get_response_value(recipes_GET_response, "per_page") == 1
    assert skyramp.get_response_value(recipes_GET_response, "has_next") == False
    assert skyramp.get_response_value(recipes_GET_response, "has_previous") == True
    assert skyramp.get_response_value(recipes_GET_response, "total_pages") >= 1


if __name__ == "__main__":
    test_integration()
