# Generated by Skyramp v1.3.23 on 2026-05-05 22:50:18.163572695 +0000 UTC m=+263.871811915
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output shopping_list_fuzzy_merge_adversarial_almond_flour_integration_test.py \
# 		--output-dir /home/runner/work/mealie/mealie/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/mealie/mealie/tests/scenario_shopping_list_fuzzy_merge_adversarial_almond_flour.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:9000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    lists = "e6f7a8b9-2013-2345-fabc-456789012345"

    # Request Body
    recipes_POST_request_body = r'''{
        "name": "almond-flour-test-1746200002"
    }'''
    
    # Execute Request
    recipes_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes",
        method="POST",
        body=recipes_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert recipes_POST_response.status_code == 201

    # Request Body
    lists_POST_request_body = r'''{
        "name": "AdversarialTest-List-1746200002"
    }'''
    
    # Execute Request
    lists_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/households/shopping/lists",
        method="POST",
        body=lists_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert lists_POST_response.status_code == 201
    assert skyramp.get_response_value(lists_POST_response, "name") == "AdversarialTest-List-1746200002"
    assert skyramp.get_response_value(lists_POST_response, "id") is not None

    # Request Body
    recipe_POST_request_body = r'''[
        {
            "recipe_id": "d5e6f7a8-1902-1234-efab-345678901234",
            "recipe_increment_quantity": 1,
            "recipe_ingredients": [
                {
                    "note": "flour",
                    "quantity": 1
                },
                {
                    "note": "almond flour",
                    "quantity": 1
                }
            ]
        }
    ]'''
    
    # Execute Request
    recipe_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/households/shopping/lists/{lists}/recipe",
        method="POST",
        body=recipe_POST_request_body,
        headers=headers,
        path_params={"lists": lists},
        query_params={"merge_strategy": ["fuzzy"]}
    )
    # Generated Assertions
    assert recipe_POST_response.status_code == 200
    assert skyramp.get_response_value(recipe_POST_response, "id") is not None
    assert skyramp.get_response_value(recipe_POST_response, "id") == skyramp.get_response_value(lists_POST_response, "id")
    assert len(skyramp.get_response_value(recipe_POST_response, "list_items")) == 2
    assert skyramp.get_response_value(recipe_POST_response, "list_items.0.note") == "flour"
    assert skyramp.get_response_value(recipe_POST_response, "list_items.1.note") == "almond flour"
    assert skyramp.get_response_value(recipe_POST_response, "list_items.2") is None


if __name__ == "__main__":
    test_integration()
